services:
  web:
    build: ./app
    command: /usr/src/app/scripts/entrypoint.sh
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    image: tenz-img-prod:latest
    expose:
      - 8000
    env_file:
      - ./.env.prod
    # depends_on:
    #   - db
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
    - static_volume:/usr/src/app/staticfiles/
    - media_volume:/usr/src/app/mediafiles/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  # postgres_data:
  static_volume:
  media_volume: