# Generated by Django 5.0 on 2024-06-22 21:52

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='content',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=200, required=False)), ('subheading', wagtail.blocks.TextBlock(label='Sub heading', max_length=400, required=False)), ('content', wagtail.blocks.RichTextBlock(editor='default'))]))], blank=True, null=True),
        ),
    ]
