# Generated by Django 5.0 on 2024-05-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='footer_logo',
            field=models.ForeignKey(blank=True, help_text='Please upload an image with dimensions 250x50 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='header_logo',
            field=models.ForeignKey(blank=True, help_text='Please upload an image with dimensions 250x50 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
