# Generated by Django 5.0 on 2024-05-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_companysettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookieconsentsettings',
            options={'verbose_name': 'Cookie Consent Settings', 'verbose_name_plural': 'Cookie Consent Settings'},
        ),
    ]
