# Generated by Django 5.0 on 2024-09-18 09:48

import streams.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalpage',
            name='header_carousel',
            field=wagtail.fields.StreamField([('carousel', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {'required': False}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'max_height': 697, 'max_width': 1920}), 3: ('wagtail.blocks.StructBlock', [[('video', 2)]], {'required': False}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'required': False, 'target_model': streams.models.CarouselVideo}), 5: ('wagtail.blocks.StructBlock', [[('video', 4)]], {'required': False}), 6: ('wagtail.blocks.StreamBlock', [[('image', 1), ('embed', 3), ('media', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('carousel_items', 6)]], {})}, null=True),
        ),
    ]
