# Generated by Django 5.0 on 2024-09-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_universalpage_header_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universalpage',
            old_name='content',
            new_name='sections',
        ),
    ]
