# Generated by Django 5.0 on 2024-05-19 13:31

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('content', wagtail.fields.StreamField([('simple_information', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=200, required=False)), ('information', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('info_type', wagtail.blocks.ChoiceBlock(choices=[('text', 'Text'), ('contact_number', 'Contact Number'), ('email', 'Email')], help_text='Select what type of info you are adding', required=False)), ('info', wagtail.blocks.CharBlock(label='Info', max_length=200, required=False))], required=False)))])), ('simple_information_with_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=200, required=False)), ('information', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('info_type', wagtail.blocks.ChoiceBlock(choices=[('text', 'Text'), ('contact_number', 'Contact Number'), ('email', 'Email')], help_text='Select what type of info you are adding', required=False)), ('info', wagtail.blocks.CharBlock(label='Info', max_length=200, required=False))], required=False))), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('timeline_information', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', max_length=200, required=False)), ('information', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('timeline', wagtail.blocks.CharBlock(label='Timeline', max_length=15, required=False)), ('heading_info', wagtail.blocks.CharBlock(label='Heading Info', max_length=200, required=False)), ('sub_info', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('info', wagtail.blocks.CharBlock(label='Info', max_length=200, required=False))], required=False)))], required=False)))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume page',
                'verbose_name_plural': 'Resume pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
