# Generated by Django 5.0 on 2024-08-31 19:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('content', wagtail.fields.StreamField([('simple_information', 5), ('simple_information_with_image', 7), ('timeline_information', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('contact_number', 'Contact Number'), ('email', 'Email')], 'help_text': 'Select what type of info you are adding', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Info', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('info_type', 1), ('info', 2)]], {'required': False}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('information', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('information', 4), ('image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Timeline', 'max_length': 15, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Heading Info', 'max_length': 200, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('info', 2)]], {'required': False}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('timeline', 8), ('heading_info', 9), ('sub_info', 11)]], {'required': False}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('information', 13)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Resume page',
                'verbose_name_plural': 'Resume pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
